global using Base.Lib.Kafka.ServiceRegistration;
global using KafkaConsumerSample.Persistence.Context;
global using KafkaConsumerSample.Persistence.Interfaces.Services;
global using KafkaConsumerSample.Persistence.ServicesRegistry;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Versioning;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.OpenApi.Models;
global using System.Text.Json.Serialization;
